# Generated by Django 5.1.2 on 2024-10-13 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_timestampedvalues_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedTimestampedValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)])),
                ('time', models.TimeField()),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1000000), django.core.validators.MaxValueValidator(1000000)])),
            ],
            options={
                'ordering': ['-year', '-month', '-day', '-time'],
                'indexes': [models.Index(fields=['year', 'month', 'day', 'time', 'value'], name='testapp_det_year_0582d8_idx')],
            },
        ),
    ]
