# Generated by Django 5.1.2 on 2024-10-14 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_detailedtimestampedvalues'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastApproach',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1000000), django.core.validators.MaxValueValidator(1000000)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)])),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['year', 'month', 'day'], name='testapp_las_year_075ab1_idx'), models.Index(fields=['timestamp'], name='testapp_las_timesta_162dd3_idx')],
            },
        ),
    ]
