# Generated by Django 5.1.2 on 2024-10-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_lastapproach'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lastapproach',
            name='testapp_las_timesta_162dd3_idx',
        ),
        migrations.AlterField(
            model_name='lastapproach',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lastapproach',
            name='timestamp',
            field=models.DateTimeField(db_index=True, unique=True),
        ),
    ]
