# Generated by Django 5.1.2 on 2024-10-14 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_remove_lastapproach_testapp_las_timesta_162dd3_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetailedTimestampedValues',
        ),
        migrations.DeleteModel(
            name='TimestampedValues',
        ),
    ]
