# Generated by Django 5.1.2 on 2024-10-14 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_delete_detailedtimestampedvalues_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateTimestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, unique=True)),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1000000), django.core.validators.MaxValueValidator(1000000)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)])),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidate Timestamp',
                'verbose_name_plural': 'Candidate Timestamps',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='LastApproach',
        ),
        migrations.AddIndex(
            model_name='candidatetimestamp',
            index=models.Index(fields=['year', 'month', 'day'], name='testapp_can_year_0b147b_idx'),
        ),
    ]
